import { Deck } from './deck.model';

export const DECKS: readonly Deck[] = [
  {
    id: 'animals',
    titleKey: 'decks.animals.title',
    imageAltKey: 'decks.animals.imageAlt',
    image: 'images/leon.png',
    imageClass: 'animals',
    language: 'chinese',
    line: 'children',
    theme: 'animals',
    age: '3-6',
    ageOrder: 1,
    cardCount: 20,
    status: 'available',
  },
  {
    id: 'fruit-and-vegetables',
    titleKey: 'decks.fruitAndVegetables.title',
    imageAltKey: 'decks.fruitAndVegetables.imageAlt',
    image: null,
    imageClass: 'fruit',
    language: 'chinese',
    line: 'children',
    theme: 'food',
    age: '3-6',
    ageOrder: 1,
    cardCount: 20,
    status: 'comingSoon',
  },
  {
    id: 'my-family',
    titleKey: 'decks.myFamily.title',
    imageAltKey: 'decks.myFamily.imageAlt',
    image: null,
    imageClass: 'family',
    language: 'chinese',
    line: 'children',
    theme: 'family',
    age: '3-6',
    ageOrder: 1,
    cardCount: 20,
    status: 'comingSoon',
  },
  {
    id: 'basic-emotions',
    titleKey: 'decks.basicEmotions.title',
    imageAltKey: 'decks.basicEmotions.imageAlt',
    image: null,
    imageClass: 'emotions',
    language: 'chinese',
    line: 'children',
    theme: 'emotions',
    age: '3-6',
    ageOrder: 1,
    cardCount: 20,
    status: 'comingSoon',
  },
  {
    id: 'numbers',
    titleKey: 'decks.numbers.title',
    imageAltKey: 'decks.numbers.imageAlt',
    image: null,
    imageClass: 'numbers',
    language: 'chinese',
    line: 'children',
    theme: 'numbers',
    age: '4-7',
    ageOrder: 2,
    cardCount: 20,
    status: 'comingSoon',
  },
  {
    id: 'weather',
    titleKey: 'decks.weather.title',
    imageAltKey: 'decks.weather.imageAlt',
    image: null,
    imageClass: 'weather',
    language: 'chinese',
    line: 'children',
    theme: 'weather',
    age: '4-7',
    ageOrder: 2,
    cardCount: 20,
    status: 'comingSoon',
  },
  {
    id: 'world-and-cultures',
    titleKey: 'decks.worldAndCultures.title',
    imageAltKey: 'decks.worldAndCultures.imageAlt',
    image: null,
    imageClass: 'world',
    language: 'chinese',
    line: 'children',
    theme: 'world',
    age: '7-11',
    ageOrder: 3,
    cardCount: 40,
    status: 'comingSoon',
    premium: true,
  },
];